### ISSUE TITLE
Examples of JSON input and output?

### ISSUE THREAD

**Issue by rafaqz** [agrafix/Spock-rest#1]
I've just set up a basic working rest server routing with spock rest, seems like a solid little framework.

But when it comes to actually returning a JSON string from various sources or doing something with JSON from a post/put body I'm struggling to work out the type system and grokking what matcherLoop is actually doing... I always end up with:

```
    Invalid request: Can not handle required Content-type.
```

It would be great if the example contained a little more detail of this.

**Comment by agrafix** [comment]
Did you set the `Content-Type` and the `Accept` Headers accordingly?

**Comment by rafaqz** [comment]
Oh yeah... works like a dream now.
